routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CategoryGroupController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\PointsTransactionController;
use App\Http\Controllers\Admin\ProfilesController;
use App\Http\Controllers\Admin\SubscriptionController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Auth\ProfileAndUserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function (){
        Route::view('/profile/create', 'auth.profiles.create')->name('profile.create');
        Route::post('/profile', [ProfileAndUserController::class, 'store'])->name('profile.store');

        Route::group(['middleware' => 'HasProfile'], function (){
            Route::view('/profile/edit', 'auth.editProfile')->name('profile.edit');
            Route::put('/profile/{profile}/update', [ProfileAndUserController::class, 'updateProfile'])->name('profile.updateProfile');
            Route::put('/login/{user}/update', [ProfileAndUserController::class, 'updateLogin'])->name('profile.updateLogin');
            Route::put('/password/{user}/update', [ProfileAndUserController::class, 'updatePassword'])->name('profile.updatePassword');
        });
    });

    Route::group(['middleware' => ['role:Admin'], 'prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::post('/user/{user}/changeRole', [UsersController::class, 'changeRole'])->name('users.changeRole');
        Route::post('/user/{user}/changeStatus', [UsersController::class, 'changeStatus'])->name('users.changeStatus');
        Route::resource('/users', UsersController::class, ['except' => ['create', 'store']]);
        Route::resource('/profiles', ProfilesController::class, ['only' => ['store', 'update', 'create']]);
        Route::resource('/category_groups', CategoryGroupController::class, ['except' => ['create']]);
        Route::post('/categories/{category_group}/', [CategoryController::class, 'store'])->name('categories.store');
        Route::resource('/categories', CategoryController::class, ['except' => ['index', 'create', 'show', 'store']]);
        Route::delete('/offers/delete/{media}', [OfferController::class, 'deleteMedia'])->name('offers.deleteMedia');
        Route::resource('/offers', OfferController::class, ['except' => ['create', 'store']]);
        Route::resource('/pointsTransactions', PointsTransactionController::class, ['except' => ['create', 'store']]);
        Route::get('/subscriptions', [SubscriptionController::class, 'index'])->name('subscriptions.index');
   });
    Route::post('/getsubscription/{subscription}', [SubscriptionController::class, 'getSubscription'])->name('getsubscription');
    Route::post('/pointstransfer/{user}', [PointsTransactionController::class, 'transfer'])->name('points.transfer');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/admin/group_category/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><strong>{{__('dashboard.group_category.edit.title')}}: {{$categoryGroup->name}}</strong></div>
            <div class="card-body">
                <form class="form-horizontal" action="{{route('admin.category_groups.update', $categoryGroup)}}"
                      method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="text-center">
                        @if(!$categoryGroup->getFirstMedia('category_group_avatars'))
                            <img src="https://via.placeholder.com/150" style="max-width: 300px" alt="">
                        @else
                            <img src="{{$categoryGroup->getFirstMediaUrl('category_group_avatars')}}" style="max-width: 300px" alt="">
                        @endif
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="name">{{__('dashboard.group_category.edit.name')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="name" type="text" name="name" autocomplete="name"
                                   value="{{old('name', $categoryGroup->name)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="avatar">{{__('dashboard.group_category.edit.avatar')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="avatar" type="file" name="avatar">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">{{__('dashboard.buttons.save_changes')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><strong>{{__('dashboard.group_category.edit.add_new_category')}}</strong></div>
            <div class="card-body">
                <form class="form-horizontal" action="{{route('admin.categories.store', $categoryGroup->id)}}" method="post">
                    @csrf
                    @method('POST')
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="name">{{__('dashboard.group_category.edit.name')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="name" type="text" name="name" autocomplete="name"
                                   value="{{old('name')}}">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">{{__('dashboard.buttons.save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i>
                <strong>{{__('dashboard.categories.index.table_title')}}</strong>
            </div>
            @if(count($categories) == NULL)
                <div class="card-body">{{__('dashboard.global.is_empty')}}</div>
            @else
                <div class="card-body">
                    <table class="table table-responsive-sm">
                        <thead>
                        <tr>
                            <th>{{__('dashboard.categories.index.title')}}</th>
                            <th>{{__('dashboard.global.offers_count')}}</th>
                            <th>{{__('dashboard.global.actions')}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $category)
                            <tr>
                                <td>{{ $category->name }}</td>
                                <td>{{ $category->offers_count }}</td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{route('admin.categories.edit', $category)}}">
                                            <svg class="btn btn-outline btn-info"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-pencil')}}"></use>
                                            </svg>
                                        </a>
                                        <button type="button" class="btn btn-primary"
                                                style="padding: 0; border: 0; display: inline"
                                                data-toggle="modal"
                                                data-target="#deleteCategoryConfirmModal">
                                            <svg class="btn btn-outline btn-danger"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-trash')}}"></use>
                                            </svg>
                                        </button>
                                        @include('admin.group_category.modals.deleteCategoryConfirmModal')

                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>

                    </table>
                </div>
                <div class="card-footer">
                    <div class="pagination">{{ $categories->links() }}</div>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/admin/group_category/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><strong>{{__('dashboard.group_category.create.title')}}</strong></div>
            <div class="card-body">
                <form class="form-horizontal" action="{{route('admin.category_groups.store')}}"
                      method="post" enctype="multipart/form-data">
                    @csrf
                    @method('POST')
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="name">{{__('dashboard.group_category.create.name')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="name" type="text" name="name" autocomplete="name"
                                   value="{{old('name')}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="avatar">{{__('dashboard.group_category.create.avatar')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="avatar" type="file" name="avatar">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">{{__('dashboard.buttons.save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i>
                <strong>{{__('dashboard.group_category.index.table_title')}}</strong>
            </div>
            <div class="card-body">
                @if(! $categoryGroups)
                    <div class="card-body">
                        {{__('dashboard.global.is_empty')}}
                    </div>
                @else
                    <table class="table table-responsive-sm">
                        <thead>
                        <tr>
                            <th>{{__('dashboard.group_category.create.avatar')}}</th>
                            <th>{{__('dashboard.global.title')}}</th>
                            <th>{{__('dashboard.global.categories_count')}}</th>
                            <th>{{__('dashboard.global.offers_count')}}</th>
                            <th>{{__('dashboard.global.actions')}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categoryGroups as $categoryGroup)
                            <tr>
                                <td>
                                    <img src="{{$categoryGroup->getFirstMediaUrl('category_group_avatars', 'thumb')}}" alt="">
                                </td>
                                <td>{{ $categoryGroup->name }}</td>
                                <td>{{ $categoryGroup->categories_count }}</td>
                                <td>{{ $categoryGroup->offers_count }}</td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{route('admin.category_groups.edit', $categoryGroup)}}">
                                            <svg class="btn btn-outline btn-info"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-pencil')}}"></use>
                                            </svg>
                                        </a>
                                        <button type="button" class="btn btn-primary"
                                                style="padding: 0; border: 0; display: inline"
                                                data-toggle="modal"
                                                data-target="#deleteCategoryGroupConfirmModal">
                                            <svg class="btn btn-outline btn-danger"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-trash')}}"></use>
                                            </svg>
                                        </button>
                                        @include('admin.group_category.modals.deleteCategoryGroupConfirmModal')

                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="pagination">{{ $categoryGroups->links() }}</div>
                @endif
            </div>
        </div>
    </div>

@endsection

resources/views/admin/group_category/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><i class="fa fa-align-justify"></i> {{__('dashboard.global.user_advertisements')}}</div>
                <div class="card-body">
                    <table class="table table-responsive-sm">
                        <thead>
                        <tr>
                            <th>{{__('dashboard.global.title')}}</th>
                            <th>{{__('dashboard.global.category_name')}}</th>
                            <th>{{__('dashboard.global.quantity')}}</th>
                            <th>{{__('dashboard.global.coast')}}</th>
                            <th>{{__('dashboard.global.exchange_type')}}</th>
                            <th>{{__('dashboard.global.status')}}</th>
                            <th>{{__('dashboard.global.actions')}}</th>
                        </tr>
                        </thead>
                        <tbody>
{{--                        @foreach($users as $user)--}}
                            <tr>
                                <td>Kawalerka</td>
                                <td>Nieruchomości. wynajem</td>
                                <td>1</td>
                                <td>1500</td>
                                <td>Punkty</td>
                                <td><span class="badge badge-success">Active</span></td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{route('admin.users.show', $user)}}">
                                            <svg class="btn btn-outline btn-light"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-info')}}"></use>
                                            </svg>
                                        </a>
                                        <a href="{{route('admin.users.edit', $user)}}">
                                            <svg class="btn btn-outline btn-info"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-pencil')}}"></use>
                                            </svg>
                                        </a>
                                        <button type="button" class="btn btn-primary"
                                                style="padding: 0; border: 0; display: inline"
                                                data-toggle="modal"
                                                data-target="#deleteUserConfirmModal">
                                            <svg class="btn btn-outline btn-danger"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-trash')}}"></use>
                                            </svg>
                                        </button>
                                    </div>
                                </td>
                            </tr>
{{--                        @endforeach--}}
                        </tbody>
                    </table>
{{--                    <div class="pagination">{{ $user->advertisements->links() }}</div>--}}
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-header">
                    {{__('dashboard.global.role')}}:
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{$user->profile->getFullName()}}</h5>
                    <p class="card-text">{{$user->profile->getFullAddress()}}</p>
                    <p class="card-text">{{$user->profile->contact_phone}}</p>
{{--                    <a href="#" class="btn btn-primary">Go somewhere</a>--}}
                </div>
                <div class="card-footer text-muted">
                    {{$user->email}}
                </div>
            </div>
        </div>
    </div>
@endsection