routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CategoryGroupController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\PointsTransactionController;
use App\Http\Controllers\Admin\ProfilesController;
use App\Http\Controllers\Admin\SubscriptionController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Auth\ProfileAndUserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function (){
        Route::view('/profile/create', 'auth.profiles.create')->name('profile.create');
        Route::post('/profile', [ProfileAndUserController::class, 'store'])->name('profile.store');

        Route::group(['middleware' => 'HasProfile'], function (){
            Route::view('/profile/edit', 'auth.editProfile')->name('profile.edit');
            Route::put('/profile/{profile}/update', [ProfileAndUserController::class, 'updateProfile'])->name('profile.updateProfile');
            Route::put('/login/{user}/update', [ProfileAndUserController::class, 'updateLogin'])->name('profile.updateLogin');
            Route::put('/password/{user}/update', [ProfileAndUserController::class, 'updatePassword'])->name('profile.updatePassword');
        });
    });

    Route::group(['middleware' => ['role:Admin'], 'prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::post('/user/{user}/changeRole', [UsersController::class, 'changeRole'])->name('users.changeRole');
        Route::post('/user/{user}/changeStatus', [UsersController::class, 'changeStatus'])->name('users.changeStatus');
        Route::resource('/users', UsersController::class, ['except' => ['create', 'store']]);
        Route::resource('/profiles', ProfilesController::class, ['only' => ['store', 'update', 'create']]);
        Route::resource('/category_groups', CategoryGroupController::class, ['except' => ['create']]);
        Route::post('/categories/{category_group}/', [CategoryController::class, 'store'])->name('categories.store');
        Route::resource('/categories', CategoryController::class, ['except' => ['index', 'create', 'show', 'store']]);
        Route::delete('/offers/delete/{media}', [OfferController::class, 'deleteMedia'])->name('offers.deleteMedia');
        Route::resource('/offers', OfferController::class, ['except' => ['create', 'store']]);
        Route::resource('/pointsTransactions', PointsTransactionController::class, ['except' => ['create', 'store']]);
        Route::get('/subscriptions', [SubscriptionController::class, 'index'])->name('subscriptions.index');
   });
    Route::post('/getsubscription/{subscription}', [SubscriptionController::class, 'getSubscription'])->name('getsubscription');
    Route::post('/pointstransfer/{user}', [PointsTransactionController::class, 'transfer'])->name('points.transfer');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\ModelStatus\HasStatuses;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes, HasRoles, HasStatuses;

    /**
     * Model statuses const and static array variable $statuses
     *
     * @var array
     */
    public const ACTIVE = 'Active';
    public const INACTIVE = 'Inactive';
    public const DEACTIVATED = 'Deactivated';

    public static $statuses_types = [self::ACTIVE, self::INACTIVE, self::DEACTIVATED];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Only accept a valid password and
     * hash a password before saving
     */
    public function setPasswordAttribute($password)
    {
        if ( $password !== null & $password !== "" )
        {
            $this->attributes['password'] = bcrypt($password);
        }
    }

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function offers()
    {
        return $this->hasMany(Offer::class);
    }

    public function transactions()
    {
        return $this->hasMany(PointsTransaction::class);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserUpdateRequest;
use App\Models\Offer;
use App\Models\PointsTransaction;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Spatie\Permission\Models\Role;

class UsersController extends Controller
{

    public function index(): View
    {
        $users = User::paginate(10);

        return view('admin.users.index', compact('users'));
    }

    public function show(User $user): View
    {
        $offers = Offer::where('user_id', $user->id)->with('category')->paginate(10);
        $transactions = PointsTransaction::where('user_id', $user->id)->paginate(10);

        return view('admin.users.show', compact('user', 'offers', 'transactions'));
    }

    public function edit(User $user): View
    {
        $statuses = User::$statuses_types;

        $roles = Role::all();

        return view('admin.users.edit', compact('user', 'roles', 'statuses'));
    }

    public function update(UserUpdateRequest $request, User $user): RedirectResponse
    {
        $user->update($request->validated());

        return back()->with('success', __('Saved correctly.'));
    }

    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return back()->with('success', __('Deleted correctly.'));
    }

    public function changeRole(User $user, Request $request): RedirectResponse
    {
        $user->roles()->detach();
        $user->roles()->sync($request->get('role'));

        return back(201)->with('success', __('Saved correctly.'));
    }

    public function changeStatus(User $user, Request $request): RedirectResponse
    {
        $user->setStatus($request->get('status'));

        return back(201)->with('success', __('Saved correctly.'));
    }
}

resources/views/admin/users/modals/deleteTransactionConfirmModal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="deleteTransactionConfirmModal">
    <form id="delete-form" action="{{route('admin.pointsTransactions.destroy', $transaction)}}" method="post">
        @csrf
        @method('DELETE')
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <strong>{{__('dashboard.points_transactions.index.confirmation_delete_transaction')}}</strong>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">{{__('dashboard.buttons.modals.modal_delete_submit_button')}}</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('dashboard.buttons.modals.modal_delete_cancel_button')}}</button>
                </div>
            </div>
        </div>
    </form>
</div>

resources/views/admin/users/modals/deleteUserConfirm.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="deleteUserConfirmModal">
    <form id="delete-form" action="{{route('admin.users.destroy', $user)}}" method="post">
        @csrf
        @method('DELETE')
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <strong>{{__('dashboard.users.index.confirmation_delete_user')}}</strong>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-danger">{{__('dashboard.buttons.modals.modal_delete_submit_button')}}</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">{{__('dashboard.buttons.modals.modal_delete_cancel_button')}}</button>
                </div>
            </div>
        </div>
    </form>
</div>