routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CategoryGroupController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\PointsTransactionController;
use App\Http\Controllers\Admin\ProfilesController;
use App\Http\Controllers\Admin\SubscriptionController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Auth\ProfileAndUserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function (){
        Route::view('/profile/create', 'auth.profiles.create')->name('profile.create');
        Route::post('/profile', [ProfileAndUserController::class, 'store'])->name('profile.store');

        Route::group(['middleware' => 'HasProfile'], function (){
            Route::view('/profile/edit', 'auth.editProfile')->name('profile.edit');
            Route::put('/profile/{profile}/update', [ProfileAndUserController::class, 'updateProfile'])->name('profile.updateProfile');
            Route::put('/login/{user}/update', [ProfileAndUserController::class, 'updateLogin'])->name('profile.updateLogin');
            Route::put('/password/{user}/update', [ProfileAndUserController::class, 'updatePassword'])->name('profile.updatePassword');
        });
    });

    Route::group(['middleware' => ['role:Admin'], 'prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::post('/user/{user}/changeRole', [UsersController::class, 'changeRole'])->name('users.changeRole');
        Route::post('/user/{user}/changeStatus', [UsersController::class, 'changeStatus'])->name('users.changeStatus');
        Route::resource('/users', UsersController::class, ['except' => ['create', 'store']]);
        Route::resource('/profiles', ProfilesController::class, ['only' => ['store', 'update', 'create']]);
        Route::resource('/category_groups', CategoryGroupController::class, ['except' => ['create']]);
        Route::post('/categories/{category_group}/', [CategoryController::class, 'store'])->name('categories.store');
        Route::resource('/categories', CategoryController::class, ['except' => ['index', 'create', 'show', 'store']]);
        Route::delete('/offers/delete/{media}', [OfferController::class, 'deleteMedia'])->name('offers.deleteMedia');
        Route::resource('/offers', OfferController::class, ['except' => ['create', 'store']]);
        Route::resource('/pointsTransactions', PointsTransactionController::class, ['except' => ['create', 'store']]);
        Route::get('/subscriptions', [SubscriptionController::class, 'index'])->name('subscriptions.index');
   });
    Route::post('/getsubscription/{subscription}', [SubscriptionController::class, 'getSubscription'])->name('getsubscription');
    Route::post('/pointstransfer/{user}', [PointsTransactionController::class, 'transfer'])->name('points.transfer');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/navs/header.blade.php
<header class="c-header c-header-light c-header-fixed c-header-with-subheader">
    <button class="c-header-toggler c-class-toggler d-lg-none mfe-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show">
        <svg class="c-icon c-icon-lg">
            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-menu')}}"></use>
        </svg>
    </button><a class="c-header-brand d-lg-none" href="#">
        <svg width="118" height="46" alt="CoreUI Logo">
            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#full')}}"></use>
        </svg></a>
    <button class="c-header-toggler c-class-toggler mfs-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true">
        <svg class="c-icon c-icon-lg">
            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-menu')}}"></use>
        </svg>
    </button>
    <ul class="c-header-nav d-md-down-none">
        <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">{{__('Dashboard')}}</a></li>
        <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">{{__('Users')}}</a></li>
        <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">{{__('Settings')}}</a></li>
    </ul>
    <ul class="c-header-nav ml-auto mr-4">
        <div class="badge badge-pill badge-success">
{{__('dashboard.subscriptions.index.points')}}: {{auth()->user()->profile->points}}
        </div>
        <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                <svg class="c-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-bell')}}"></use>
                </svg></a></li>
        <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                <svg class="c-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-list-rich')}}"></use>
                </svg></a></li>
        <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                <svg class="c-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-envelope-open')}}"></use>
                </svg></a></li>
        <li class="c-header-nav-item dropdown">
            <a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                <div class="c-avatar">
                    @if(!auth()->user()->profile || !auth()->user()->profile->getFirstMedia('user_avatars'))
                        <img class="c-avatar-img" src="https://barter-test.s3.eu-west-1.amazonaws.com/icons/user.png"
                             alt="{{auth()->user()->email}}">
                    @else
                        <img class="c-avatar-img" src="{{auth()->user()->profile->getFirstMediaUrl('user_avatars', 'thumb')}}"
                             alt="{{auth()->user()->email}}">
                    @endif
                </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right pt-0">
                <div class="dropdown-header bg-light py-2"><strong>{{__('Account')}}</strong></div>

                <a class="dropdown-item" href="{{route('auth.profile.edit')}}">

{{--                    <a class="dropdown-item" href="#">--}}
                        <svg class="c-icon mr-2">
                            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-user')}}"></use>
                        </svg>
                    {{__('Profile')}}
                </a>
                <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();">
                        <svg class="c-icon mr-2">
                            <use xlink:href="vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                        </svg>
                        {{__('Log out')}}
                    </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                </a>
            </div>
        </li>
    </ul>
</header>

resources/views/layouts/navs/sidebar.blade.php
<div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
    <div class="c-sidebar-brand d-lg-down-none">
        <svg class="c-sidebar-brand-full" width="118" height="46" alt="CoreUI Logo">
            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#full')}}"></use>
        </svg>
        <svg class="c-sidebar-brand-minimized" width="46" height="46" alt="CoreUI Logo">
            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#signet')}}"></use>
        </svg>
    </div>
    <ul class="c-sidebar-nav ps">
        <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="{{route('home')}}">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-speedometer')}}"></use>
                </svg> Dashboard</a></li>
        <li class="c-sidebar-nav-title">{{__('dashboard.global.sidebar.admin_section')}}</li>

        <!-- Users mangement sections -->
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown  {{ (request()->is('admin/users/*')) ? 'c-show' : '' }}">
            <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-people')}}"></use>
                </svg>
                {{__('dashboard.global.sidebar.user_management')}}
            </a>
            <ul class="c-sidebar-nav-dropdown-items">
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="{{route('admin.users.index')}}"><span class="c-sidebar-nav-icon"></span>
                        {{__('dashboard.global.sidebar.users')}}
                    </a>
                </li>
{{--                <li class="c-sidebar-nav-item">--}}
{{--                    <a class="c-sidebar-nav-link" href="{{route('admin.users.index')}}"><span class="c-sidebar-nav-icon"></span>--}}
{{--                        {{__('dashboard.global.roles')}}--}}
{{--                    </a>--}}
{{--                </li>--}}
            </ul>
        </li>
        <!--   Category groups section -->
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown {{ (request()->is('admin/category_groups/*')) ? 'c-show' : '' }}">
            <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-clear-all')}}"></use>
                </svg>
                {{__('dashboard.global.sidebar.category_groups')}}
            </a>
            <ul class="c-sidebar-nav-dropdown-items">
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="{{route('admin.category_groups.index')}}">
                        {{__('dashboard.global.sidebar.category_groups_management')}}
                    </a>
                </li>
                <div class="dropdown-divider"></div>
                @foreach(\App\Models\CategoryGroup::all()->sortBy('name') as $group)
                    <li class="c-sidebar-nav-item">
                        <a class="c-sidebar-nav-link" href="{{route('admin.category_groups.edit', $group)}}">
                            {{ $group->name }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </li>

        <!-- Offers section -->
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown {{ (request()->is('admin/offers/*')) ? 'c-show' : '' }}">
            <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-chart-line')}}"></use>
                </svg>
                {{__('dashboard.global.offers')}}
            </a>
            <ul class="c-sidebar-nav-dropdown-items">
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="{{route('admin.offers.index')}}">
                        {{__('dashboard.global.list')}}
                    </a>
                </li>
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="">
                        {{__("dashboard.global.settings")}}
                    </a>
                </li>
            </ul>
        </li>

        <!-- Transactions section -->
        <li class="c-sidebar-nav-item c-sidebar-nav-dropdown {{ (request()->is('admin/pointsTransactions/*')) ? 'c-show' : '' }}">
            <a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                <svg class="c-sidebar-nav-icon">
                    <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-money')}}"></use>
                </svg>
                {{__('dashboard.global.sidebar.transactions')}}
            </a>
            <ul class="c-sidebar-nav-dropdown-items">
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link" href="{{route('admin.pointsTransactions.index')}}">
                        {{__('dashboard.global.list')}}
                    </a>
                </li>
            </ul>
        </li>

        <li class="c-sidebar-nav-title">{{__('dashboard.global.sidebar.user_section')}}</li>
        <div class="ps__rail-x" style="left: 0px; bottom: 0px;"><div class="ps__thumb-x" tabindex="0" style="left: 0px; width: 0px;"></div></div>
        <div class="ps__rail-y" style="top: 0px; right: 0px;"><div class="ps__thumb-y" tabindex="0" style="top: 0px; height: 0px;"></div></div>
    </ul>
    <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
</div>