routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CategoryGroupController;
use App\Http\Controllers\Admin\OfferController;
use App\Http\Controllers\Admin\PointsTransactionController;
use App\Http\Controllers\Admin\ProfilesController;
use App\Http\Controllers\Admin\SubscriptionController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Auth\ProfileAndUserController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function (){
    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function (){
        Route::view('/profile/create', 'auth.profiles.create')->name('profile.create');
        Route::post('/profile', [ProfileAndUserController::class, 'store'])->name('profile.store');

        Route::group(['middleware' => 'HasProfile'], function (){
            Route::view('/profile/edit', 'auth.editProfile')->name('profile.edit');
            Route::put('/profile/{profile}/update', [ProfileAndUserController::class, 'updateProfile'])->name('profile.updateProfile');
            Route::put('/login/{user}/update', [ProfileAndUserController::class, 'updateLogin'])->name('profile.updateLogin');
            Route::put('/password/{user}/update', [ProfileAndUserController::class, 'updatePassword'])->name('profile.updatePassword');
        });
    });

    Route::group(['middleware' => ['role:Admin'], 'prefix' => 'admin', 'as' => 'admin.'], function(){
        Route::post('/user/{user}/changeRole', [UsersController::class, 'changeRole'])->name('users.changeRole');
        Route::post('/user/{user}/changeStatus', [UsersController::class, 'changeStatus'])->name('users.changeStatus');
        Route::resource('/users', UsersController::class, ['except' => ['create', 'store']]);
        Route::resource('/profiles', ProfilesController::class, ['only' => ['store', 'update', 'create']]);
        Route::resource('/category_groups', CategoryGroupController::class, ['except' => ['create']]);
        Route::post('/categories/{category_group}/', [CategoryController::class, 'store'])->name('categories.store');
        Route::resource('/categories', CategoryController::class, ['except' => ['index', 'create', 'show', 'store']]);
        Route::delete('/offers/delete/{media}', [OfferController::class, 'deleteMedia'])->name('offers.deleteMedia');
        Route::resource('/offers', OfferController::class, ['except' => ['create', 'store']]);
        Route::resource('/pointsTransactions', PointsTransactionController::class, ['except' => ['create', 'store']]);
        Route::get('/subscriptions', [SubscriptionController::class, 'index'])->name('subscriptions.index');
   });
    Route::post('/getsubscription/{subscription}', [SubscriptionController::class, 'getSubscription'])->name('getsubscription');
    Route::post('/pointstransfer/{user}', [PointsTransactionController::class, 'transfer'])->name('points.transfer');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Admin/PointsTransactionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Offer;
use App\Models\PointsTransaction;
use App\Models\Profile;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;


class PointsTransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $pointsTransactions = PointsTransaction::with('statuses', 'offer')->where('subscription', 0)->latest()->paginate(20);
        $subscriptions = PointsTransaction::subscription()->latest()->paginate(20);

        return view('admin.points_transactions.index', compact('pointsTransactions', 'subscriptions'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     * Soft delete
     *
     * @param PointsTransaction $pointTransaction
     * @return RedirectResponse
     */
    public function destroy(PointsTransaction $pointTransaction): RedirectResponse
    {
        $pointTransaction->delete();

        return back(201)->with('success', __('Deleted correctly.'));
    }

    public function transfer($id)
    {
        $offer = Offer::with('user')->findOrFail($id);
        $authUserPoints = auth()->user()->profile->points;
        $userPoints = $offer->user->profile->points;

        if ($offer->coast > $authUserPoints)
            return back()->with('error', 'Nie masz tylu punktów na koncie');

        auth()->user()->profile->update(['points' => $authUserPoints - $offer->coast]);

        Profile::unsetEventDispatcher();
        $offer->user->profile->update(['points' => $userPoints + $offer->coast]);

        PointsTransaction::create([
            'user_id' => auth()->id(),
            'transaction_type' => PointsTransaction::OUTGOING,
            'transfer_to' => $offer->user->id,
            'transfer_from' => auth()->id(),
            'completed_at' => now(),
            'description' => 'Payment for the item',
            'amount' => $offer->coast,
            'offer_id' => $offer->id
        ])->setStatus(PointsTransaction::SUCCESS);

        return back()->with('success', 'Wszystko poszło ok :)');
    }
}

resources/views/admin/points_transactions/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><strong>{{__('dashboard.profile.edit_form.login_information\'s')}}</strong></div>
            <div class="card-body">
                <form class="form-horizontal" action="{{route('admin.users.update', $user)}}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="name">{{__('dashboard.users.edit_form.name')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="name" type="text" name="name" autocomplete="name"
                                   value="{{old('name', $user->name)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="email">{{__('dashboard.global.email_address')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="email" type="email" name="email" autocomplete="email"
                                   value="{{old('email', $user->email)}}">
                        </div>
                    </div>
                    <div class="card-footer">
                            <button class="btn btn-sm btn-primary" type="submit">{{__('dashboard.buttons.save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><strong>{{__('dashboard.global.role')}}</strong></div>
            <div class="card-body">
                <form class="form-horizontal" action="{{route('admin.users.changeRole', $user)}}" method="post">
                    @csrf
                    @method('POST')
                    <div class="form-group">
                        <label for="role">{{__('dashboard.users.edit_form.change_role_label')}}</label>
                        <select name="role" id="role" class="form-control">
                            @foreach($roles as $role)
                                <option
                                    {{ ($user->roles->pluck('name')->implode(' ') == $role->name ? 'selected' : '')}}
                                    value="{{$role->id}}">
                                    {{$role->name}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">{{__('dashboard.buttons.save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><strong>{{__('dashboard.global.status')}}</strong></div>
            <div class="card-body">
                <form class="form-horizontal" action="{{route('admin.users.changeStatus', $user)}}" method="post">
                    @csrf
                    @method('POST')
                    <div class="form-group">
                        <label for="status">{{__('dashboard.users.edit_form.change_status_label')}}</label>
                        <select name="status" id="status" class="form-control">
                            @foreach($statuses as $status)
                                <option
                                    {{ ($user->status == $status ? 'selected' : '')}}
                                    value="{{$status}}">
                                    {{$status}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">{{__('dashboard.buttons.save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header"><strong>{{__('dashboard.users.edit_form.user_profile')}}</strong></div>
            <div class="card-body">
                <form class="form-horizontal" action="{{route('admin.profiles.update', $user->profile)}}"
                      method="post">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="first_name">{{__('dashboard.profile.edit_form.first_name')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="first_name" type="text" name="first_name" autocomplete="name"
                                   value="{{old('first_name', $user->profile->first_name)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="surname">{{__('dashboard.profile.edit_form.surname')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="surname" type="text" name="surname" autocomplete="surname"
                                   value="{{old('surname', $user->profile->surname)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="country">{{__('dashboard.profile.edit_form.country')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="country" type="text" name="country" autocomplete="country"
                                   value="{{old('country', $user->profile->country)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="city">{{__('dashboard.profile.edit_form.city')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="city" type="text" name="city" autocomplete="city"
                                   value="{{old('city', $user->profile->city)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="postal_code">{{__('dashboard.profile.edit_form.postal_code')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="postal_code" type="text" name="postal_code" autocomplete="postal_code"
                                   value="{{old('postal_code', $user->profile->postal_code)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="street">{{__('dashboard.profile.edit_form.street')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="street" type="text" name="street" autocomplete="street"
                                   value="{{old('street', $user->profile->street)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="number">{{__('dashboard.profile.edit_form.number')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="number" type="text" name="number" autocomplete="number"
                                   value="{{old('number', $user->profile->number)}}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-md-3 col-form-label" for="contact_phone">{{__('dashboard.profile.edit_form.contact_phone')}}</label>
                        <div class="col-md-9">
                            <input class="form-control" id="contact_phone" type="text" name="contact_phone" autocomplete="contact_phone"
                                   value="{{old('contact_phone', $user->profile->contact_phone)}}">
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-sm btn-primary" type="submit">{{__('dashboard.buttons.save')}}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/points_transactions/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header"><i class="fa fa-align-justify"></i> <strong>{{__('dashboard.points_transactions.index.title')}}</strong></div>
            <div class="card-body">
                <table class="table table-responsive-sm">
                    <thead>
                    <tr>
                        <th>{{__('dashboard.global.username')}}</th>
                        <th>{{__('dashboard.points_transactions.index.transaction_type')}}</th>
                        <th>{{__('dashboard.points_transactions.index.created_at')}}</th>
                        <th>{{__('dashboard.points_transactions.index.amount')}}</th>
                        <th>{{__('dashboard.points_transactions.index.user_from')}}</th>
                        <th>{{__('dashboard.points_transactions.index.user_to')}}</th>
                        <th>{{__('dashboard.global.status')}}</th>
                        <th>{{__('dashboard.points_transactions.index.completed_at')}}</th>
                        <th>{{__('dashboard.global.description')}}</th>
                        <th>{{__('dashboard.global.offer')}}</th>
                        <th>{{__('dashboard.global.actions')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($pointsTransactions as $subscription)
                        <tr>
                            <td>{{ $subscription->user->name }}</td>
                            <td>{{ $subscription->transaction_type }}</td>
                            <td>{{ $subscription->created_at }}</td>
                            <td>{{ $subscription->amount }}</td>
                            <td>{{ $subscription->transfer_from }}</td>
                            <td>{{ $subscription->transfer_to }}</td>
                            <td><span class="badge badge-success">{{ $subscription->status }}</span></td>
                            <td>{{ $subscription->completed_at }}</td>
                            <td>{{ $subscription->description }}</td>
                            <td>
                                @if(! $subscription->offer)
                                    <p style="color: red;">{{__('dashboard.global.subscription')}}</p>
                                @else
                                    <a href="{{route('admin.offers.show', $subscription->offer)}}">
                                        {{ $subscription->offer->title }}
                                    </a>
                                @endif
                            </td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a href="{{route('admin.pointsTransactions.edit', $subscription)}}">
                                        <svg class="btn btn-outline btn-info"
                                             style="max-height: 25px; max-width: 25px; padding: 3px">
                                            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-pencil')}}"></use>
                                        </svg>
                                    </a>
                                    <button type="button" class="btn btn-primary"
                                            style="padding: 0; border: 0; display: inline"
                                            data-toggle="modal"
                                            data-target="#deleteTransactionConfirmModal">
                                        <svg class="btn btn-outline btn-danger"
                                             style="max-height: 25px; max-width: 25px; padding: 3px">
                                            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-trash')}}"></use>
                                        </svg>
                                    </button>
                                    @include('admin.points_transactions.modals.deleteTransactionConfirmModal')
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pagination">{{ $pointsTransactions->links() }}</div>
            </div>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header"><i class="fa fa-align-justify"></i> <strong>{{__('dashboard.points_transactions.index.title_second_table')}}</strong></div>
            <div class="card-body">
                <table class="table table-responsive-sm">
                    <thead>
                    <tr>
                        <th>{{__('dashboard.global.username')}}</th>
                        <th>{{__('dashboard.points_transactions.index.transaction_type')}}</th>
                        <th>{{__('dashboard.points_transactions.index.created_at')}}</th>
                        <th>{{__('dashboard.points_transactions.index.amount')}}</th>
                        <th>{{__('dashboard.global.status')}}</th>
                        <th>{{__('dashboard.points_transactions.index.completed_at')}}</th>
                        <th>{{__('dashboard.global.description')}}</th>
                        <th>{{__('dashboard.global.actions')}}</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($subscriptions as $subscription)
                        <tr>
                            <td>{{ $subscription->user->name }}</td>
                            <td>{{ $subscription->transaction_type }}</td>
                            <td>{{ $subscription->created_at }}</td>
                            <td>{{ $subscription->amount }}</td>
                            <td><span class="badge badge-success">{{ $subscription->status }}</span></td>
                            <td>{{ $subscription->completed_at }}</td>
                            <td>{{ $subscription->description }}</td>
                            <td>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    <a href="{{route('admin.pointsTransactions.edit', $subscription)}}">
                                        <svg class="btn btn-outline btn-info"
                                             style="max-height: 25px; max-width: 25px; padding: 3px">
                                            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-pencil')}}"></use>
                                        </svg>
                                    </a>
                                    <button type="button" class="btn btn-primary"
                                            style="padding: 0; border: 0; display: inline"
                                            data-toggle="modal"
                                            data-target="#deleteTransactionConfirmModal">
                                        <svg class="btn btn-outline btn-danger"
                                             style="max-height: 25px; max-width: 25px; padding: 3px">
                                            <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-trash')}}"></use>
                                        </svg>
                                    </button>
                                    @include('admin.points_transactions.modals.deleteTransactionConfirmModal')
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="pagination">{{ $pointsTransactions->links() }}</div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/points_transactions/show.blade.php
@extends('layouts.app')
@section('content')
        <div class="col-md-12">
            <div class="card text-center">
                <div class="card-header">
                    {{__('dashboard.global.role')}}: <strong>{{$user->roles->pluck('name')->implode(' ')}}</strong>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{$user->profile->getFullName()}}</h5>
                    <p class="card-text">{{$user->profile->getFullAddress()}}</p>
                    <p class="card-text">{{$user->profile->contact_phone}}</p>
                    {{--                    <a href="#" class="btn btn-primary">Go somewhere</a>--}}
                </div>
                <div class="card-footer text-muted">
                    {{$user->email}}
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><i class="fa fa-align-justify"></i> {{__('dashboard.global.user_offers')}}</div>
                <div class="card-body">
                    <table class="table table-responsive-sm">
                        <thead>
                        <tr>
                            <th>{{__('dashboard.global.title')}}</th>
                            <th>{{__('dashboard.global.offer_type')}}</th>
                            <th>{{__('dashboard.global.category_name')}}</th>
{{--                            <th>{{__('dashboard.global.quantity')}}</th>--}}
                            <th>{{__('dashboard.global.coast')}}</th>
                            <th>{{__('dashboard.global.payment_type')}}</th>
                            <th>{{__('dashboard.global.status')}}</th>
                            <th>{{__('dashboard.global.actions')}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($offers as $offer)
                            <tr>
                                <td>{{ $offer->title }}</td>
                                <td>{{ $offer->offer_type }}</td>
                                <td><strong>{{ $offer->category->categoryGroup->name }}</strong> > {{ $offer->category->name }}</td>
                                <td>{{ $offer->coast }}</td>
                                <td>
                                    {{ $offer->payment_type }}<br>
                                    @if($offer->payment_type == 'exchange')
                                        <small>{{ $offer->exchange_for }}</small>
                                    @endif
                                </td>
                                <td><span class="badge badge-success">{{ $offer->status }}</span></td>
                                <td>
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{route('admin.users.show', $user)}}">
                                            <svg class="btn btn-outline btn-light"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-info')}}"></use>
                                            </svg>
                                        </a>
                                        <a href="{{route('admin.users.edit', $user)}}">
                                            <svg class="btn btn-outline btn-info"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-pencil')}}"></use>
                                            </svg>
                                        </a>
                                        <button type="button" class="btn btn-primary"
                                                style="padding: 0; border: 0; display: inline"
                                                data-toggle="modal"
                                                data-target="#deleteUserConfirmModal">
                                            <svg class="btn btn-outline btn-danger"
                                                 style="max-height: 25px; max-width: 25px; padding: 3px">
                                                <use xlink:href="{{asset('vendors/@coreui/icons/svg/free.svg#cil-trash')}}"></use>
                                            </svg>
                                        </button>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="pagination">{{ $offers->links() }}</div>
                </div>
            </div>
        </div>
@endsection